<?php

namespace Database\Seeders;

use App\Models\Type;
use Illuminate\Database\Seeder;

class TypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $types = [
            'Ability Boost'         => 'An ability that grants a permanent boost to one of your Ability Scores',
            'Ability Damage'        => 'An effect that causes Ability Score Damage',
            'Abjuration'            => 'Effects and magic items with this trait are associated with the abjuration school of magic, typically involving protections, wards, or counterspells.',
            'Aberration'            => 'Things from the Far Realm or created or modified by the Far Realm or something from the Far Realm',
            'Acid'                  => 'Effects with this trait deal acid damage. An item with Hardness 5 or lower takes 1 extra Dent from acid damage. Creatures with this trait have a connection to acid.',
            'Activate'              => 'An action with this trait is used as part of the Activate an item activity.',
            'Additive'              => "Alchemists use additives. Feats with this trait allow you to spend actions to add special substances to bombs or elixirs. You can add only one additive to a single alchemical item, and attempting to add another spoils the item. You can typically take actions with the additive trait only when you're creating an infused alchemical item, and some can be used only with teh Quick Alchemy action.",
            'Agile'                 => 'You cau use up to 2 points of your DEX modifier as a bonus to Hit instead of your STR modifier when making Melee attacks with the Agile weapon',
            'Aid'                   => 'Pertaining to the Aid Another Action',
            'Air'                   => 'Effects with the air trait either manipulate or conjure air. Those that manipulate air have no effect in a vacuum or an area without air. Creatures with this trait consist primarily of air or have a connection to the element.',
            'Alchemical'            => "Alchemical items are powered by reactions of alchemical reagents, sometimes sparked by the user’s Resonance Points. Alchemical items aren't magical, and they don’t radiate a magical aura. Characters can Craft these items only if they have the Alchemist feat.",
            'Ammunition'            => '',
            'Ancestry'              => 'An ability that is obtainable due to racial characteristics',
            'Animal'                => 'An animal is a creature with a relatively low Intelligence. They typically do not have an INT ability score over 3, can’t speak languages, and can’t be trained in INT-based skills.',
            'Animal Companion'      => '',
            'Animate'               => '',
            'Arcane'                => 'This spell or magic item comes from an arcane spellcaster or from the arcane magical tradition.',
            'Archon'                => 'Concerning the celestials that inhabit the Seven Heavens',
            'Armor'                 => '',
            'Artificer'             => '',
            'Artificer Discipline'  => '',
            'Astral'                => '',
            'Attached'              => "An attached weapon must be combined with another piece of gear to be used. The trait lists what type of item the weapon must be attached to. You must be wielding or wearing the item the weapon is attached to in order to attack with it. For example, shield spikes are attached to a shield bash, but only if you're wielding the shield. An attached weapon is usually bolted onto or built into the item it's attached to, and typically an item can have only one weapon attached to it. An attached weapon can be affixed to an item with 10 minutes of work and a successful DC 10 Crafting check; this includes the time needed to remove the weapon from a previous item, if necessary. If an item is destroyed, its attached weapon can usually be salvaged.",
            'Attack'                => 'This ability grants an attack or is made through an attack.',
            'Attack of Opportunity' => '',
            'Attunement'            => 'An ability that has to do Attuning to magical items or a magical item that requires Attunement',
            'Auditory'              => 'Auditory actions and effects rely on sound. An action with the auditory trait can be successfully performed only if the creature using the action can speak or otherwise produce the required sounds. A spell or effect with the auditory trait has its effect only if the target can hear it. This is different from a sonic effect, which still affects targets who can’t hear it (such as deaf targets) as long as the effect makes sound.',
            'Aura'                  => '',
            'Axe'                   => '',
            'Backstabber'           => 'When you hit a flat-footed creature, this weapon deals an additional 2 precision damage. If the weapon is of Expert quality, it deals 3 precision damage instead.',
            'Backswing'             => "You can use this weapon's momentum from a miss to lead into your next attack. After missing with this weapon on your turn, you gain a +1 circumstance bonus to your next attack with this weapon before the end of your turn.",
            'Banishing'             => '',
            'Bardic Inspiration'    => '',
            'Bardic Muse'           => '',
            'Battle Cry'            => 'Spells that have a Verbal Casting and have a very short duration during combat',
            'Beast'                 => '',
            'Bless'                 => 'A bless is an effect that places some benefit on a creature. Blesses are always magic.',
            'Bloodline'             => '',
            'Bludgeoning'           => 'Damage type caused by blunt force trauma',
            'Bomb'                  => 'Alchemical bombs are a type of alchemical item that must be thrown instead of activated. Most of them explode, dealing damage to their target and splash damage to other nearby creatures.',
            'Bow'                   => '',
            'Calling'               => 'An effect that physically draws a creature to your current plane',
            'Channel Divinity'      => '',
            'Chronomancy'           => 'Magic school pertaining to the manipulation of and traversing time',
            'Cantrip'               => 'A spell with this trait can be cast at will and automatically heightens to the highest level spell you can cast.',
            'Celestial'             => 'Any Outsider from the Upper Planes',
            'Chaotic'               => 'Chaotic effects often manipulate energy from chaos- aligned Outer Planes and are anathema to lawful divine servants or divine servants of lawful deities. A creature with this trait is chaotic in alignment. An ability with this trait can be selected or used by chaotic creatures only.',
            'Charge'                => 'If you moved at least 10 feet on the action before your attack, add a circumstance bonus to damage for that attack equal to the number of damage dice for the weapon.',
            'Circle Magic'          => '',
            'Charm'                 => '',
            'Clairsentience'        => 'Psionic discipline of precognition. Clairsentience enables you to learn secrets long forgotten, to glimpse the immediate future and predict the future, to find hidden objects, and to know what is normally unknowable. It also has the closest connection to raw psionics, and can both detect, disrupt and disable psionics.',
            'Club'                  => '',
            'Cold'                  => 'Effects with this trait deal cold damage. Creatures with this trait have a connection to magical cold.',
            'Combat Mastery'        => 'Category of effects pertaining to improvements in combat skill',
            'Compulsion'            => 'Sub-school of Illusion that forces a target to behave or believe a certain way, or alters the way their mind works',
            'Concentrate'           => 'It takes a degree of mental concentration and discipline to use this type of action.',
            'Conjuration'           => 'Effects and magic items with this trait are associated with the conjuration school of magic, typically involving summoning, creation, teleportation, or moving things from place to place.',
            'Construct'             => 'Pertaining to creatures that are not organic in nature',
            'Consumable'            => '<p>An item with this trait can be used only once. Unless stated otherwise, the item is destroyed after activation, though in some cases, part of it might be recoverable for other purposes. For instance, while a potion is a consumable item, the vial the potion comes in is not destroyed after the potion is activated.</p>
<p>When a character creates consumable items, she can make them in batches of four, as described in the Craft activity</p>',
            'Contact'               => 'This poison activates on touch.',
            'Counterspell'          => 'Pertaining to the cancellation of a magical effect',
            'Creation'              => 'Pertaining to effects that create something from something else',
            'Cumbersome'            => 'While wearing this armor, you have Disadvantage on DEX checks',
            'Curse'                 => 'A curse is an effect that places some affliction on a creature. Curses are always magic and are typically the result of a spell or trap.',
            'Cursed'                => 'A creature with the Cursed type has its origins in some curse or punishment',
            'Damage Reduction'      => 'Regarding a form of Armor that reduces any Physical Damage by the specified amount.',
            'Darkness'              => 'Darkness effects extinguish light in the area, including less powerful magical light. Darkness and light effects can negate one another.',
            'Deadly'                => 'On a critical hit, a weapon with this trait adds a weapon damage die of the listed size. This damage increases to two dice if the weapon is master quality and three dice if the weapon is legendary. For instance, a master-quality rapier deals 2d6 additional piercing damage on a critical hit.',
            'Death'                 => 'A death effect kills living creatures more easily.',
            'Demodand'              => 'Concerning the fiends that are imprisoned Carceri',
            'Demon'                 => 'Concerning the fiends that inhabit the infinite Abyss',
            'Detection'             => 'Effects with this trait attempt to determine the presence or location of a person, thing, or aura. Most effects with the detection trait also have the divination trait.',
            'Derro'                 => '',
            'Devil'                 => 'Concerning the fiends that inhabit the Nine Hells of Baator',
            'Diminishing'           => 'An attack that becomes less effective the more it is used against the same target in the same encounter.',
            'Disarm'                => "You can use this weapon to Disarm with the Athletics skill even if you don't have a free hand. This uses the weapon's reach (if different from your own) and adds the weapon’s item bonus to attack rolls (if any) as a bonus to the Athletics check. If you critically fail a check to Disarm using the weapon, you can drop the weapon to treat it as a normal failure. On a critical success, you still need a free hand if you want to take the item.",
            'Discipline'            => 'Monk feats that define the origin of their power. A character can have only one Discipline feat',
            'Disease'               => 'Effects with this trait apply one or more diseases. Diseases are typically afflictions.',
            'Disorienting'          => 'Spells that affect the mind in ways that hinder normal thought and/or activity',
            'Divination'            => 'Effects and magic items with this trait are associated with the divination school of magic, typically involving obtaining or transferring information.',
            'Divine'                => 'This spell or magic item comes from divine power, from a divine spellcaster, or from the divine magical tradition.',
            'Divine Warrior'        => '',
            'Downtime'              => 'This ability can be used only during the downtime between adventures.',
            'Domain'                => '',
            'Dragon'                => '',
            'Drow'                  => '',
            'Drug'                  => '',
            'Duergar'               => '',
            'Dwarf'                 => 'A creature with this trait is one of the dwarves, stout folk who often live underground and typically have darkvision. An ability with this trait can be used or chosen only by dwarves. A weapon with this trait is created and used by dwarves.',
            'Earth'                 => 'Effects with the earth trait either manipulate or conjure earth. Those that manipulate earth have no effect in an area without earth. Creatures with this trait consist primarily of earth or have a connection to the element.',
            'Earth Node'            => '',
            'Ectoplasm'             => 'A pseudo stuff of the Ethereal Plane',
            'Eladrin'               => 'Concerning the Celestials that inhabit Arvandor',
            'Electricity'           => 'Effects with this trait deal electricity damage. A creature with this trait has a magical connection to electricity.',
            'Elemental'             => 'Pertaining to the Inner Elemental planes or creatures or objects from those planes',
            'Elf'                   => 'A creature with this trait is one of the elves, mysterious people with rich traditions of magic and scholarship who typically have low-light vision. An ability with this trait can be used or chosen only by elves. A weapon with this trait is created and used by elves.',
            'Elixir'                => 'The alchemical items called elixirs must be drunk to be activated.',
            'Emotion'               => 'These effects alter a creature’s emotions. Creatures with special training or that have mechanical or artificial intelligence are immune to emotion effects.',
            'Enchantment'           => 'Effects and magic items with this trait are associated with the enchantment school of magic, typically involving raw magical energy, fields of magic, and long lasting magical effects that can enhance, inhibit, or otherwise modify creatures and objects.',
            'Ethereal'              => 'Concerning the Ethereal Plane',
            'Evil'                  => 'Evil effects often manipulate energy from evil-aligned Outer Planes and are anathema to good divine servants or divine servants of good deities. A creature with this trait is evil in alignment. An ability with this trait can be selected or used by evil creatures only.',
            'Evocation'             => 'Effects and magic items with this trait are associated with the evocation school of magic, typically involving energy and other elemental forces.',
            'Exalted'               => 'Pertaining to effects that are divine and celestial in origin',
            'Extra Action'          => 'An effect that grants additional Actions',
            'Extradimensional'      => 'This effect or item creates an extradimensional space. An extradimensional effect placed inside another extradimensional space ceases to function until it is removed.',
            'Faithful Steed'        => '',
            'Familiar'              => '',
            'Fatal'                 => "The fatal trait includes a die size. On a critical hit, all the weapon's damage dice increase to that die size instead of the normal size, and another weapon damage die size instead of the normal size, and another weapon damage die of the listed size is added to the damage roll.",
            'Favored'               => 'Feats or Features that are related to the Favored Soul class',
            'Favored Enemy'         => 'Pertaining to the Ranger ability of increased combat ability against certain species or closely studied opponents',
            'Favored Terrain'       => 'Pertaining to the Ranger ability of improved ability while in certain environments',
            'Fear'                  => 'Fear effects evoke the emotion of fear. Effects with this trait always have the mental and emotion trait as well.',
            'Feint'                 => 'Pertaining to the Combat Action that is meant to distract an opponent',
            'Fey'                   => 'Pertaining to creatures and objects that are originally from the FeyWild',
            'Fiend'                 => 'Any Outsider from the Lower Planes',
            'Fighter Feat'          => 'A specific category of Feats mostly centered around Combat and that fighter types are focused on',
            'Figment'               => 'This spell creates an image or sound that is not real',
            'Finesse'               => 'You may use the Weapon Finesse feat with this weapon',
            'Finisher'              => 'Finishers are spectacular attacks that use your Panache',
            'Fire'                  => 'Pertaining to the Element of Fire',
            'Flanking'              => 'When an opponent is engaged in melee from 2 or more allies that are on opposite sides of the opponent',
            'Force'                 => 'Effects with this trait deal force damage or create objects made of pure magical force.',
            'Forceful'              => 'This weapon becomes more dangerous when you build up momentum. When you attack with the weapon more than once on your turn, the second attack adds a circumstance bonus to damage equal to the number weapon damage dice, and each subsequent attack adds a circumstance bonus to damage equal to double the number of weapon damage dice.',
            'Formula'               => 'Pertaining to the instructions that are needed to create specific items',
            'Fortune'               => '',
            'Fragile'               => "If fragile armor takes a Dent, it's automatically broken.",
            'Free-Hand'             => "This weapon doesn't take up your hand, usually because it is built into your armor. A free-hand weapon can't be Disarmed. You can use the hand covered by your free-hand weapon to wield other items, perform Manipulate Actions, and so on. You can't attack with a free-hand weapon if you're wielding anything in that hand or otherwise using that hand. WHen you're not wielding anything and not otherwise using the hand, you can use abilities that require you to have a hand free as well as those that require you to be wielding a weapon in that hand. Each of your hands can have only one free-hand weapon on it",
            'Generic'               => 'Feats that any class may take',
            'Giant'                 => 'Pertaining to the category of creatures that are of the god Annam',
            'Glamor'                => 'This spell fools the senses (makes something look like something else or fool a sense into sensing something else)',
            'Gnoll'                 => 'Pertaining to the race of creatures and the god Yeenoghu',
            'Gnome'                 => 'Pertaining to the race of creatures and their gods',
            'Goblin'                => 'A creature with this trait can come from multiple tribes of creatures, including small and canny goblins, militaristic hobgoblins, and hulking, savage bugbears. Goblins tend to have darkvision. An ability with this trait can be used or chosen only by goblins. A weapon with this trait is created and used by goblins.',
            'Good'                  => 'Good effects often manipulate energy from good-aligned Outer Planes and are anathema to evil divine servants or divine servants of evil deities. A creature with this trait is good in alignment. An ability with this trait can be selected or used only by good creatures.',
            'Graft'                 => 'Pertaining to the act of modifying organic bodies with other organic bodies from a different creature',
            'Grapple'               => "You can use this weapon to Grapple with the Athletics skill even if you don't have a free hand. THis uses the weapon's reach (if different from your own) and adds the weapon's item bonus to attack rolls as an item bonus to the Athletics check. If you Critically Fail a check to Grapple using the weapon, you can drop the weapon to take the effects of a Failure instead of a Critical Failure",
            'Guardinal'             => 'Concerning the Celestials that Inhabit Elysium',
            'Half-Elf'              => 'A creature with this trait is part human and part elf. An ability with this trait can be used or chosen only by half-elves.',
            'Halfling'              => 'Pertaining to the race of creatures and their gods',
            'Half-Orc'              => 'A creature with this trait is part human and part orc. An ability with this trait can be used or chosen only by half-orcs.',
            'Harm'                  => '',
            'Healing'               => 'A healing effect restores a creature’s body in some way, typically by restoring Hit Points, but sometimes by removing other debilitating effects.',
            'Heritage'              => 'Ancestry feats that have the heritage trait are feats that your character can select only at 1st level. Unlike with other feats, you cannot retrain your character to learn a heritage feat or to change her existing heritage feat at any point. Your character can never have more than one heritage feat.',
            'Heroic Surge'          => 'Pertaining to the ability to the class ability to take additional Actions or trigger certain abilities',
            'High Magic'            => 'A spell with this type requires the High Magic feat to cast for spells of 3rd level or lower and the Olin Gisir feat to cast higher level spells.',
            'Human'                 => 'A creature with this trait is one of the humans, a diverse array of people known for their adaptability. An ability with this trait can be used or chosen only by humans.',
            'Humanoid'              => 'Humanoid creatures reason and act much like humans. They typically stand upright and have two arms and two legs.',
            'Illusion'              => 'Effects and magic items with this trait are associated with the illusion school of magic, typically involving false or magically altered sensory stimuli, and mental manipulations, compulsions, and even mind control.',
            'Incorporeal'           => 'Pertaining to the ability to enter the Ethereal Plane from the Prime Material Plane',
            'Infusion'              => '',
            'Ingested'              => 'Category of drugs and poisons that requires them to be eaten or drunk to take effect',
            'Inhaled'               => 'Category of drugs and poisons that requires them to be breathed in to take effect',
            'Initiative'            => 'Referring to or modifying your initiative in combat',
            'Injury'                => 'Category of drugs and poisons that requires them to be administered through the skin to take effect',
            'Invocation'            => '',
            'Item Creation'         => 'Pertaining to the act of creating magical items or mundane items that requires a certain level of ability in specific skills',
            'Jousting'              => 'The weapon is suited for mounted combat with a harness or similar means. When mounted, if you moved at least 10 feet on the Action before your attack, add a circumstance bonus to damage for that attack equal to the number of damage dice for the weapon. In addition, while mounted, you can wield the weapon in one hand, changing the damage die to the listed value',
            'Kobold'                => 'Pertaining to the race of creatures and their god',
            'Lawful'                => 'Lawful effects often manipulate energy from law-aligned Outer Planes and are anathema to chaotic divine servants or divine servants of chaotic deities. A creature with this trait is lawful in alignment. An ability with this trait can be selected or used by lawful creatures only.',
            'Light'                 => 'Light effects generate light. Darkness and light effects can negate one another.',
            'Lightweight'           => 'You can wear this armor without having the necessary armor proficiency, provided your biology allows. Constitution checks made to maintain concentration while wearing lightweight armor you are not proficient with are made with Disadvantage',
            'Lingual'               => '',
            'Lizard'                => '',
            'Lycanthrope'           => 'Pertaining to the curse that forces a creature to transform into an animal version of themselves or to creatures born of them',
            'Magical'               => '',
            'Manipulate'            => 'A category of Actions that has to do with using or activating an item or object',
            'Mechanical'            => '',
            'Melee'                 => '',
            'Mental'                => 'Mental spells affect the target’s mind. They have no effect on mindless creatures or objects. Mental can also appear as a damage type for spells that deal damage through psychic trauma.',
            'Metamagic'             => 'Metamagic feats trigger when you begin casting a spell and typically require you to spend an additional spellcasting action to alter the spell’s effects. You can’t use metamagic feats if adding an action to the spell would make the spell require more actions than you have remaining on your turn. Because most metamagic feats have the same trigger, you usually can’t use more than one metamagic feat per spell.',
            'Metacreativity'        => 'Psionic discipline of matter manipulation. Metacreativity powers create objects, creatures, or some form of matter. Creatures you create usually, but always, obey your commands. A metacreativity power draws raw ectoplasm from the Astral Plane to create an object or creature in the place of the psionic character designates. Objects created in this fashion are as solid and durable as normal objects, despite their originally diaphanous substance. Psionic creatures created with metacreativity powers are considered Constructs, not outsiders.',
            'Metapsionic'           => '',
            'Mind Blade'            => '',
            'Mindless'              => 'A mindless creature has either programmed or rudimentary mental attributes. Most, if not all, of their mental ability scores are 1. They are immune to all mental effects.',
            'Minion'                => 'A creature with this trait can use only 2 actions per turn and can’t use reactions. A minion acts on your turn in combat when you spend an action to issue it verbal commands (this action has the concentrate trait). If given no commands, minions use no actions except to defend themselves or to escape obvious harm. If left unattended for at least 1 minute, mindless minions don’t act, whereas intelligent ones act as they please.',
            'Modron'                => 'Concerning the Outsiders that inhabit Mechanus',
            'Monstrosity'           => 'A category of creatures that are usually magically created by mortals but have become self sustaining in the wild',
            'Morph'                 => '',
            'Mounted'               => '',
            'Move'                  => 'A category of Actions that have to do with movement',
            'Necromancy'            => 'Category of magic that has to do with life, death and the undead',
            'Negative'              => 'Pertaining to the Plane of negative life or the energy from that Plane',
            'Neutral'               => '',
            'Nonlethal'             => 'Attacks with this weapon are nonlethal, and are used to knock creatures unconscious instead of killing them. You can use a nonlethal weapon make a lethal attack with a -2 circumstance penalty',
            'Ogre'                  => '',
            'Oil'                   => '',
            'Open'                  => "You can use an Action with this trait if you haven't used an Action with the Attack or Open trait yet this turn",
            'Ooze'                  => '',
            'Orc'                   => 'Pertaining to the race of creatures and their gods',
            'Outer Planes'          => 'Pertaining to the Planes of existence that are the furthest from the Prime Material Plane or the various creatures from those Planes',
            'Outsider'              => 'Any being from the Outer Planes',
            'Pact'                  => 'Pertaining to the arrangement between mortals and powers that grants the mortal greater magical abilities and the power gains a willing agent',
            'Parry'                 => 'This weapon can be used defensively to block attacks. While wielding this weapon, if you have proficiency with it, you can spend an Action to position your weapon defensively, gaining a +1 circumstance bonus to AC until the start of your next turn',
            'Panache'               => 'Pertaining to the Swashbuckler ability',
            'Permanency'            => 'Spells or effects that can be augmented with the Permanency spell',
            'Persistent'            => '',
            'Phantasm'              => 'This spell pulls a thought from someones mind, who believes it to be real and can cause harm to the thoughts owner. Only the thoughts owner can sense and therefore be harmed by it',
            'Piercing'              => 'Causes damage by penetrating or puncturing',
            'Plant'                 => '',
            'Poison'                => 'These effects deliver a poison or deal poison damage. An item with the poison trait is poisonous and might cause an affliction',
            'Polymorph'             => 'These effects transform the target into a new form. Neither a creature nor an object can be under the effect of more than one polymorph effect at a time. If a creature or object comes under the effect of a second polymorph effect, the second polymorph effect dispels the first one. Unless otherwise stated, spells with the polymorph trait don’t allow the target to take on the appearance of a specific creature, but rather just a generic creature of a general type or ancestry.',
            'Polearm'               => '',
            'Portal'                => '',
            'Positive'              => 'Effects with this trait heal living creatures with positive energy, deal positive energy damage to undead, or manipulate positive energy.',
            'Possession'            => '',
            'Potent'                => '',
            'Potion'                => 'Category of magic items that one can drink to gain their benefits',
            'Precision'             => 'You hit the target in a vulnerable spot. Precision damage is weak against armor. If the target has Damage Reduction, apply the Damage Reduction to both the Weapon damage and the Precision damage. If the Weapon damage is less than the Damage Reduction, the all of the Precision damage is also negated.',
            'Prediction'            => '',
            'Primal'                => 'Pertaining to druid or ranger abilities',
            'Propulsive'            => 'You add half your STR modifier (if possible) to damage rolls with a propulsive ranged weapon. If you hav ea negative STR modifier, you add 0 instead',
            'Psionic'               => '',
            'Psionic Combat'        => 'Psionic power used in psychic combat',
            'Psionic Focus'         => '',
            'Psychokinesis'         => "Psionic discipline of energy manipulation. Psychokinesis powers manipulate energy or tap the power of the mind to produce a desired end. Many of these powers produce spectacular effects above and beyond the power's standard display, such as moving, melting, transforming, or blasting a target.",
            'Psychometabolism'      => 'Psionic discipline of the body. Psychometabolism powers change the physical properties fo some creature, thing, or condition. Psychometabolism also involves the healing of living flesh',
            'Psychoportation'       => 'Psionic discipline of space and time. Psychoportation powers moves the manifester, an object, or another creature through space and time.',
            'Rage'                  => '',
            'Ranged'                => '',
            'Ray'                   => 'Pertaining to effects that project a single beam of energy',
            'Reach'                 => 'This weapon is long and can be used to attack creatures up to 10 feet away instead of only adjacent creatures. FOr creatures that already have reach with the limb or limbs that wield the weapon, the weapon increase their reach by 5 feet. You suffer a -2 penalty to hit creatures that are inside your reach (that is adjacent to you)',
            'Reaction'              => 'Category of Actions that can only be taken outside of your initiative order',
            'Ritual'                => 'Pertaining to a spell that can be cast as a Ritual, or a Formula that describes a Ritual',
            'Rogue'                 => 'Pertaining to the class',
            'Rune'                  => '',
            'Scroll'                => 'Category of magic items that one must be able to and then read to trigger the spell it contains',
            'Scrying'               => 'Pertaining to effects that provide remote information gathering through visual and/or audio means',
            'Secret'                => '',
            'Shadow'                => 'Magic with this trait manipulates or depends on shadows or the energy of the Shadow Plane. Spells with this trait can create semi-real illusions that can deal real damage',
            'Shadow Weave'          => "Pertaining to the secret weave that Shar has created to combat Mystra's weave",
            'Shapechanger'          => 'Category of creatures that have the ability to change their shape into one or more different forms',
            'Shield'                => 'Pertaining to shields and the use of shields',
            'Shove'                 => 'You can use this weapon to Shove with the Athletics skill even if you don’t have a free hand. This uses the weapon’s reach (if different from your own) and adds the weapon’s item bonus to attack rolls (if any) as a bonus to the Athletics check. If you critically fail a check to Shove using the weapon, you can drop the weapon to treat the outcome as a normal failure.',
            'Skill'                 => 'A feat with the skill trait improves your skills and their uses or gives you new uses for a skill.',
            'Skirmish'              => '',
            'Slaad'                 => 'Concerning the Outsiders that inhabit Limbo',
            'Slashing'              => 'Damage type that is caused by sharp edges',
            'Smite'                 => '',
            'Sneak Attack'          => '',
            'Sonic'                 => 'An effect with the sonic trait functions only if it makes sound, meaning it has no effect in an area of silence or in a vacuum. This is different than an auditory spell, which is effective only if the target can hear it. A sonic effect might deal sonic damage.',
            'Special'               => 'A material with the special trait is harder to find or work than normal. They can be substituted for base materials when you are constructing items.',
            'Spellcasting'          => 'This action is used as part of the Cast a Spell activity.',
            'Spellthief'            => 'Pertaining to the class',
            'Spell Pool'            => 'An amount of energy spell casters can use for various effects',
            'Spirit'                => '<p>These creatures are usually from other plains of existence.</p>
<ul>
    <li>All incorporeal undead</li>
    <li>All fey</li>
    <li>All elementals</li>
    <li>Creatures in astral form or with bodies (but not a creature physically present on the Astral Plane)</li>
</ul>',
            'Splash'                => 'When a character uses a thrown weapon with the splash trait (such as an alchemical bomb or holy water), she doesn’t add her Strength modifier to the damage roll. A splash weapon can deal splash damage in addition to its normal damage. If an attack with a splash weapon fails, succeeds, or critically succeeds, all creatures within 5 feet of the target take the indicated amount of splash damage. On a failure (but not a critical failure), the target of the attack also takes the splash damage. Splash damage is not multiplied on a critical hit.',
            'Staff'                 => 'This magic item holds spells of a particular theme. A spellcaster who has invested a staff can expend their own spells or charges held in the staff to cast the spells.',
            'Strike'                => 'A category of Actions that have to do with making an attack',
            'Stride'                => 'A category of Actions that have to do with movement',
            'Sudden Strike'         => '',
            'Sword'                 => '',
            'Stance'                => 'A stance is a general combat strategy that you enter by using an Action with the stance trait, and you remain in that stance for some time. A stance lasts until you get knocked out, until its requirements (if any) are violated, until the encounter ends, or until you enter a new stance, whichever comes first. You can enter or be in a stance only in encounter mode.',
            'Summoning'             => 'Pertaining to effects that draws forth an avatar of a creature from a different Plane of existence to your current Plane',
            'Sweep'                 => 'This weapon makes wide-sweeping or spinning attacks, making it easier to attack multiple enemies. When you attack with this weapon, you gain a +1 circumstance bonus to your attack roll if you already attempted an attack this turn against a creature other than the target of this attack.',
            'Talent'                => 'An ability that is lesser than a Feat or something that grants a Talent',
            'Tattoo'                => 'Pertaining to magical or psionic writings on flesh that grants a persistent effect or allows the casting of a Spell or manifesting a Power',
            'Telepathy'             => 'Psionic discipline of the mind. Telepathy powers can spy on and affect the minds of others, influencing or controlling their behavior. Most telepathy powers are mind-affecting.',
            'Teleportation'         => 'Teleportation effects allow you to instantaneously move from one point in space to another. Teleportation does not usually trigger reactions based on movement.',
            'Thrown'                => 'You can throw this weapon as a ranged attack. A thrown weapon adds your Strength modifier to damage just like a melee weapon does. When this trait appears on a melee weapon, it also includes the range in feet. Ranged weapons with this trait can be thrown at a range equal to the weapon’s specified range.',
            'Time'                  => '',
            'Titan'                 => '',
            'Totem'                 => 'Abilities with the totem trait require a specific totem, and you lose access to them temporarily when you perform actions that are anathema to your totem. Barbarian characters choose totems.',
            'Transmutation'         => 'Effects and magic items with this trait are associated with the transmutation school of magic, typically involving changing the qualities or form of one thing into another.',
            'Trap'                  => 'A hazard or item with this trait is purposefully placed or constructed to hinder interlopers.',
            'Trinket'               => '',
            'Trip'                  => "You can use this weapon to Trip with the Athletics skill even if you don't have a free hand. This uses the weapon's reach (if different from your own) and adds the weapon's item bonus to attack rolls as an item bonus to the Athletics check. If you Critically Fail a check to Trip using the weapon, you can drop the weapon to take the effects of a Failure instead of a Critical Failure",
            'Twin'                  => "These weapons are used as a pair, each complementing the other. When you are wielding two of the same weapon with this trait and attack with one of them, if you already attacked with the other weapon this turn, you add a circumstance bonus to the damage roll equal to the weapon's number of damage dice. For instance, if you attacked with a twin weapon in your right hand with your first action, you would gain this bonus to damage when you attack with a matching twin weapon in your left hand for your second action. On your third action, an attack with either weapon would receive this bonus, since you'd already attacked with both. The weapons must be of the same type to benefit from this trait, but they don't need to be the same quality or have the same runes.",
            'Two-Hand'              => 'This weapon can be wielded with two hands. This increases its weapon damage die to the indicated value. If this trait applies to a magic weapon, the extra weapon damage dice from it being a magic weapon also increases to the indicated damage die while it’s being wielded with two hands.',
            'Unarmed'               => "An unarmed attack is made using your body rather than a manufactured weapon. An unarmed attack isn’t a weapon, though it’s categorized with weapons for weapon tables and weapon groups, and it might have weapon traits. Because it’s a part of your body, an unarmed attack can’t be Disarmed. It also doesn't take up a hand, though a fist or other grasping appendage follows the same rules as a free-hand weapon.",
            'Unarmored Defense'     => 'Category of effects that offers an AC bonus based on one of your Ability Scores',
            'Undead'                => 'Once living, these creatures were infused after death with negative energy and soul-corrupting evil magic. When reduced to 0 Hit Points, an undead creature is destroyed. Undead creatures are damaged by positive energy, are healed by negative energy, and don’t benefit from healing effects.',
            'Versatile'             => 'A versatile weapon can be used to deal a different type of damage than the type listed in the damage entry. This trait indicates the alternate damage type. For instance, a piercing weapon that has versatile S can be used to deal piercing or slashing damage. You choose the damage type each time you make an attack.',
            'Vile'                  => 'Category of effects that are evil in nature',
            'Virulent'              => 'This affliction is harder to remove.',
            'Visual'                => 'A visual spell can affect only creatures that can see it.',
            'Volley'                => 'This ranged weapon is less effective at close distances. Your attacks take a –2 penalty against targets that are at a distance within the number of feet listed.',
            'Wand'                  => 'A wand is a stick or similar object containing a spell that can be cast a certain number of times.',
            'Water'                 => 'Effects with the water trait either manipulate or conjure water. Those that manipulate water have no effect in an area without water. Creatures with this trait consist primarily of water or have a connection to the element.',
            'Wild Shape'            => 'Pertaining to the Druid ability to change shape into some form of animal',
            'Wizard School'         => 'Pertaining to the categorization of the various arcane spells',
            'Yugoloth'              => 'Pertaining the fiends that inhabit Gehenna, Hades and Tartarus',
        ];

        ksort($types);

        $app        = app();
        $app->types = [];

        foreach ($types as $name => $description) {
            $type              = new Type;
            $type->name        = $name;
            $type->description = $description;
            $type->save();

            $types        = $app->types;
            $types[$name] = $type;
            $app->types   = $types;
        }
    }
}
